# Generated by Django 2.2.6 on 2019-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=20)),
                ('ch', models.IntegerField()),
                ('obj', models.TextField(max_length=1000)),
                ('docente', models.CharField(max_length=150)),
            ],
        ),
    ]
