# Generated by Django 2.2.6 on 2019-10-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plana',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.Docente'),
        ),
    ]
