# Generated by Django 2.2.6 on 2019-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_aula', '0002_auto_20191028_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plana',
            name='docente',
            field=models.IntegerField(),
        ),
    ]
