# Generated by Django 2.2.6 on 2019-10-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan_aula', '0003_auto_20191028_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plana',
            name='docente',
            field=models.CharField(max_length=150),
        ),
    ]
