# Generated by Django 2.2.6 on 2019-10-30 18:10

import Plan_aula.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Plan_aula', '0005_auto_20191028_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='plana',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(Plan_aula.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
