# Generated by Django 2.2.6 on 2019-10-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plan_aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('proced', models.TextField(max_length=1000)),
                ('recursos', models.CharField(max_length=100)),
                ('plana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan_aula.PlanA')),
            ],
        ),
    ]
